<a href="https://colab.research.google.com/github/chinnapaht/My_Datascience_Materials/blob/master/Basic_Matrix_and_9_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
!pip install category_encoders

Collecting category_encoders
  Downloading https://files.pythonhosted.org/packages/44/57/fcef41c248701ee62e8325026b90c432adea35555cbc870aff9cfba23727/category_encoders-2.2.2-py2.py3-none-any.whl (80kB)
     |████████████████████████████████| 81kB 2.6MB/s
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (0.10.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (0.5.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (1.4.1)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (1.18.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (0.22.2.post1)
Requirement already satisfied: pandas>=0.21.1 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (1.0.3)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from patsy>=0.5.1->category_encoders) (1.12.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.20.0->category_encoders) (0.14.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.21.1->category_encoders) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.21.1->category_encoders) (2018.9)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.2.2

In [54]:
import numpy as np
M=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]]) #Matrix
v=np.array([[1],[2],[3]]) #Vector

array([[1],
       [2],
       [3]])

In [56]:
print(e.shape)
print(v+v)
print(3*v)

(3, 3)
[[2]
 [4]
 [6]]
[[3]
 [6]
 [9]]

In [76]:
m.dot(v)

array([[14],
       [32],
       [50]])

In [88]:
# Define the headers since the data does not have any
headers = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"]

# Read in the CSV file and convert "?" to NaN
df = pd.read_csv("http://mlr.cs.umass.edu/ml/machine-learning-databases/autos/imports-85.data",
                  header=None, names=headers, na_values="?" )
df.head()

   symboling  normalized_losses         make  ... city_mpg highway_mpg    price
0          3                NaN  alfa-romero  ...       21          27  13495.0
1          3                NaN  alfa-romero  ...       21          27  16500.0
2          1                NaN  alfa-romero  ...       19          26  16500.0
3          2              164.0         audi  ...       24          30  13950.0
4          2              164.0         audi  ...       18          22  17450.0

[5 rows x 26 columns]

In [89]:
#1 Hot encoding
df_encoded=pd.get_dummies(df,prefix=["encode"],columns=["num_doors"])
df_encoded.head()

   symboling  normalized_losses         make  ...    price encode_four encode_two
0          3                NaN  alfa-romero  ...  13495.0           0          1
1          3                NaN  alfa-romero  ...  16500.0           0          1
2          1                NaN  alfa-romero  ...  16500.0           0          1
3          2              164.0         audi  ...  13950.0           1          0
4          2              164.0         audi  ...  17450.0           1          0

[5 rows x 27 columns]

In [90]:
#2Label Encoding
df.loc[:,"num_door_encode"]=pd.factorize(df['num_doors'])[0].reshape(-1,1)
df

     symboling  normalized_losses  ...    price num_door_encode
0            3                NaN  ...  13495.0               0
1            3                NaN  ...  16500.0               0
2            1                NaN  ...  16500.0               0
3            2              164.0  ...  13950.0               1
4            2              164.0  ...  17450.0               1
..         ...                ...  ...      ...             ...
200         -1               95.0  ...  16845.0               1
201         -1               95.0  ...  19045.0               1
202         -1               95.0  ...  21485.0               1
203         -1               95.0  ...  22470.0               1
204         -1               95.0  ...  22625.0               1

[205 rows x 27 columns]

In [92]:
#3 Ordinal Encoding
Door_dict ={"two":2,"four":4}
df["num_doors_ordinal"]=df.num_doors.map(Door_dict)  
df

     symboling  normalized_losses  ... num_door_encode num_doors_ordinal
0            3                NaN  ...               0               2.0
1            3                NaN  ...               0               2.0
2            1                NaN  ...               0               2.0
3            2              164.0  ...               1               4.0
4            2              164.0  ...               1               4.0
..         ...                ...  ...             ...               ...
200         -1               95.0  ...               1               4.0
201         -1               95.0  ...               1               4.0
202         -1               95.0  ...               1               4.0
203         -1               95.0  ...               1               4.0
204         -1               95.0  ...               1               4.0

[205 rows x 28 columns]

In [97]:
#4 Helmert Encoding 
import category_encoders as ce
encoder=ce.HelmertEncoder(cols=["num_doors"],drop_invariant=True)
dfh=encoder.fit_transform(df["num_doors"])
df=pd.concat([df,dfh],axis=1)
df

     symboling  normalized_losses  ... num_doors_0 num_doors_1
0          3.0                NaN  ...        -1.0        -1.0
1          3.0                NaN  ...        -1.0        -1.0
2          1.0                NaN  ...        -1.0        -1.0
3          2.0              164.0  ...         1.0        -1.0
4          2.0              164.0  ...         1.0        -1.0
..         ...                ...  ...         ...         ...
200        NaN                NaN  ...         0.0         2.0
201        NaN                NaN  ...         0.0         2.0
202        NaN                NaN  ...         0.0         2.0
203        NaN                NaN  ...         0.0         2.0
204        NaN                NaN  ...         0.0         2.0

[410 rows x 32 columns]

In [99]:
#5 Binary Encoding 
encoder=ce.BinaryEncoder(cols=["num_doors"])
dfbin=encoder.fit_transform(df["num_doors"])
df=pd.concat([df,dfbin],axis=1)
df

     symboling  normalized_losses  ... num_doors_1 num_doors_2
0          3.0                NaN  ...           0           1
1          3.0                NaN  ...           0           1
2          1.0                NaN  ...           0           1
3          2.0              164.0  ...           1           0
4          2.0              164.0  ...           1           0
..         ...                ...  ...         ...         ...
200        NaN                NaN  ...           1           1
201        NaN                NaN  ...           1           1
202        NaN                NaN  ...           1           1
203        NaN                NaN  ...           1           1
204        NaN                NaN  ...           1           1

[410 rows x 35 columns]

In [101]:
#6 Freq encoding
fe=df.groupby("num_doors").size()/len(df)
df.loc[:,"num_doors_freq_encode"]=df["num_doors"].map(fe)
df

     symboling  normalized_losses  ... num_doors_2 num_doors_freq_encode
0          3.0                NaN  ...           1              0.217073
1          3.0                NaN  ...           1              0.217073
2          1.0                NaN  ...           1              0.217073
3          2.0              164.0  ...           0              0.278049
4          2.0              164.0  ...           0              0.278049
..         ...                ...  ...         ...                   ...
200        NaN                NaN  ...           1                   NaN
201        NaN                NaN  ...           1                   NaN
202        NaN                NaN  ...           1                   NaN
203        NaN                NaN  ...           1                   NaN
204        NaN                NaN  ...           1                   NaN

[410 rows x 36 columns]

In [102]:
#7 Mean Encoding
mean_encode=df.groupby("num_doors")["price"].mean()
print(mean_encode)
df.loc[:,"numdoors_mean_enc"]=df["num_doors"].map(mean_encode)
df

num_doors
four    13565.672566
two     12818.127907
Name: price, dtype: float64

     symboling  normalized_losses  ... num_doors_freq_encode numdoors_mean_enc
0          3.0                NaN  ...              0.217073      12818.127907
1          3.0                NaN  ...              0.217073      12818.127907
2          1.0                NaN  ...              0.217073      12818.127907
3          2.0              164.0  ...              0.278049      13565.672566
4          2.0              164.0  ...              0.278049      13565.672566
..         ...                ...  ...                   ...               ...
200        NaN                NaN  ...                   NaN               NaN
201        NaN                NaN  ...                   NaN               NaN
202        NaN                NaN  ...                   NaN               NaN
203        NaN                NaN  ...                   NaN               NaN
204        NaN                NaN  ...                   NaN               NaN

[410 rows x 37 columns]

In [104]:
# 8 Weight Evidence Encoding
#We Calculate probability of target = 1 i.e. Good=1 for each Category
woe_df=df.groupby("num_doors")["price"].mean()
woe_df=pd.DataFrame(woe_df)
#Rename the colum to good
woe_df=woe_df.rename(columns={"price":"Good"})
#Calculate Bad Which is 1-good prob
woe_df["Bad"]=1-woe_df.Good
#We need to add a small value to avoid divide by zero denominator
woe_df["Bad"]=np.where(woe_df["Bad"] == 0 ,0.000001,woe_df["Bad"])
#compute the WOE
woe_df["WoE"] = np.log(woe_df.Good/woe_df.Bad)
woe_df

/usr/local/lib/python3.6/dist-packages/pandas/core/series.py:679: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

                   Good           Bad  WoE
num_doors
four       13565.672566 -13564.672566  NaN
two        12818.127907 -12817.127907  NaN

In [0]:
# 9 Prob Ratio Encoding
#We Calculate probability of target = 1 i.e. Good=1 for each Category
woe_df=df.groupby("num_doors")["price"].mean()
woe_df=pd.DataFrame(woe_df)
#Rename the colum to good
woe_df=woe_df.rename(columns={"price":"Good"})
#Calculate Bad Which is 1-good prob
woe_df["Bad"]=1-woe_df.Good
#We need to add a small value to avoid divide by zero denominator
woe_df["Bad"]=np.where(woe_df["Bad"] == 0 ,0.000001,woe_df["Bad"])
#compute the Probability Ratio
woe_df["WoE"] = np.log(woe_df.Good/woe_df.Bad)
woe_df